language: java
jdk:
  - openjdk14

sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database forum;' -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)

install: true
script: mvn clean package -DskipTests=true

notifications:
  email:
    recipients:
      -BogomoloffPD@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN='5fcfd3a2-c6f2-46a3-b0c5-d1137a5afeaa'
