language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database forum;' -U postgres

sudo: false
install: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      -BogomoloffPD@yandex.ru
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN='5fcfd3a2-c6f2-46a3-b0c5-d1137a5afeaa'
